name: PR-builder

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Lint
        shell: bash
        run: npx nx affected:lint

      - name: Test
        shell: bash
        run: npx nx affected:test

      - name: Build
        shell: bash
        run: npx nx affected:build
